# VSCode
if ($null -ne (Get-Command code).Name) {
  # code --install-extension TabNine.tabnine-vscode
  code --install-extension 4ops.terraform
  code --install-extension aaron-bond.better-comments
  code --install-extension ban.spellright
  code --install-extension buster.ndjson-colorizer
  code --install-extension christian-kohler.path-intellisense
  code --install-extension CoenraadS.bracket-pair-colorizer
  code --install-extension DanSnow.vscode-dockerfilelint
  code --install-extension DavidAnson.vscode-markdownlint
  code --install-extension DominicVonk.parameter-hints
  code --install-extension DominicVonk.vscode-resx-editor
  code --install-extension dongfg.vscode-beancount-formatter
  code --install-extension donjayamanne.githistory
  code --install-extension DotJoshJohnson.xml
  code --install-extension eamodio.gitlens
  code --install-extension EditorConfig.EditorConfig
  code --install-extension emmanuelbeziat.vscode-great-icons
  code --install-extension esbenp.prettier-vscode
  code --install-extension eservice-online.vs-sharper
  code --install-extension ex-codes.pine-script-syntax-highlighter
  code --install-extension exiasr.hadolint
  code --install-extension formulahendry.code-runner
  code --install-extension formulahendry.docker-explorer
  code --install-extension foxundermoon.shell-format
  code --install-extension Fr43nk.seito-openfile
  code --install-extension GitHub.copilot
  code --install-extension GitHub.github-vscode-theme
  code --install-extension GitHub.vscode-pull-request-github
  code --install-extension Gruntfuggly.todo-tree
  code --install-extension IBM.output-colorizer
  code --install-extension iceworks-team.iceworks-time-master
  code --install-extension jeff-hykin.better-dockerfile-syntax
  code --install-extension jgclark.vscode-todo-highlight
  code --install-extension Lencerf.beancount
  code --install-extension leodevbro.blockman
  code --install-extension mechatroner.rainbow-csv
  code --install-extension mhutchie.git-graph
  code --install-extension ms-azure-devops.azure-pipelines
  code --install-extension ms-azuretools.vscode-azureresourcegroups
  code --install-extension ms-azuretools.vscode-azurevirtualmachines
  code --install-extension ms-azuretools.vscode-docker
  code --install-extension MS-CEINTL.vscode-language-pack-zh-hans
  code --install-extension ms-dotnettools.csharp
  code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
  code --install-extension ms-python.python
  code --install-extension ms-python.vscode-pylance
  code --install-extension ms-toolsai.jupyter
  code --install-extension ms-toolsai.jupyter-keymap
  code --install-extension ms-toolsai.jupyter-renderers
  code --install-extension ms-vscode-remote.remote-containers
  code --install-extension ms-vscode-remote.remote-wsl
  code --install-extension ms-vscode.azure-account
  code --install-extension ms-vscode.powershell
  code --install-extension oderwat.indent-rainbow
  code --install-extension PKief.material-icon-theme
  code --install-extension pnp.polacode
  code --install-extension redhat.vscode-yaml
  code --install-extension saekiraku.rainbow-fart
  code --install-extension samghelms.jupyter-notebook-vscode
  code --install-extension sgoley.lookml-syntax-highlighter
  code --install-extension shakram02.bash-beautify
  code --install-extension Shan.code-settings-sync
  code --install-extension shardulm94.trailing-spaces
  code --install-extension shd101wyy.markdown-preview-enhanced
  code --install-extension streetsidesoftware.code-spell-checker
  code --install-extension SumitSaha.learn-with-sumit-theme
  code --install-extension swyphcosmo.spellchecker
  code --install-extension TamasGBarna.whalelint
  code --install-extension Tim-Koehler.helm-intellisense
  code --install-extension timonwong.shellcheck
  code --install-extension TylerLeonhardt.vscode-inline-values-powershell
  code --install-extension uctakeoff.vscode-counter
  code --install-extension usernamehw.errorlens
  code --install-extension vincaslt.highlight-matching-tag
  code --install-extension VisualStudioExptTeam.vscodeintellicode
  code --install-extension waderyan.gitblame
  code --install-extension yzhang.markdown-all-in-one
  code --install-extension zhuangtongfa.material-theme
}